version: '3.4'

services:
  consul_socialmedia:
    image: hashicorp/consul:latest

  sqlserver_socialmedia:
    image: mcr.microsoft.com/mssql/server
   
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: src/server/Gateway/Gateway.Api/Dockerfile

  identityserver.api:
    image: ${DOCKER_REGISTRY-}identityserverapi
    build:
      context: .
      dockerfile: src/server/IdentityServer/IdentityServer.Api/Dockerfile


  posts.api:
    image: ${DOCKER_REGISTRY-}postsapi
    build:
      context: .
      dockerfile: src/server/Posts/Posts.Api/Dockerfile


  socialmediaapp.aggregator:
    image: ${DOCKER_REGISTRY-}socialmediaappaggregator
    build:
      context: .
      dockerfile: src/server/Gateway/SocialMediaApp.Aggregator/Dockerfile

